name: Setting and Testing

on: [workflow_dispatch]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '3.0.1'
      - name: Install dependencies
        run: bundle install
      - name: Install webpacker
        run: rails webpacker:install
      - name: Run tests cucumber
        run: cucumber
      - name: Run test rspec
        run: rspec
      - name: Rubocop
        run: rubocop -A --fail-level error